/* §7 QA harness — generates 4 weeks of posts for 3 realistically-messy trainer
   profiles under all 4 voices, asserts the grammar/quality invariants, and
   dumps every post to tests/sample-posts.md for a human read.

   Run:  node tests/content-quality.js            (expects a server on PORT below)
   or:   PORT=4615 node --env-file .env server.js  then run this.
*/
const puppeteer = require('../node_modules/puppeteer');
const fs = require('fs');
const path = require('path');
const URL = process.env.CONTENT_URL || 'http://localhost:4619/content';

// Three trainers with deliberately different answer styles.
const PROFILES = {
  'fragment-writer': {
    audience: 'men over 35', outcome: 'get strong again', core: 'lift heavy and eat enough',
    mistake1: 'do endless cardio', mistake2: 'skip protein', mistake3: 'program-hop',
    turning_point: 'I stopped chasing motivation', has_proof: 'client', proofName: 'J.',
    proofResult: 'down 24 lbs', proofBelief: 'they had no time', objection: 'no time',
    contrarian: 'cardio is the least important thing', voice: 'blunt'
  },
  'sentence-writer': {
    audience: 'men over 35, mostly desk-job guys who used to be athletes and want to feel like themselves again',
    audience_short: 'men over 35',
    outcome: 'finally get strong again without wrecking their knees or living in the gym',
    core: 'the thing I care about most is helping them eat enough protein and train with actual intent',
    mistake1: 'they train really hard in the gym and then eat like they didn’t do anything at all',
    mistake2: 'they only ever train the muscles they can see in the mirror', mistake3: 'they wait until they feel motivated',
    turning_point: 'I was skinny-fat and tired for years, and one day I finally got honest about what I was eating',
    has_proof: 'self', selfResult: 'down 30 lbs and I have kept it off for two years now', old_belief: 'that I just needed more willpower',
    before: 'skinny-fat, exhausted, hiding from every photo', objection: 'they think they cannot afford it', voice: 'warm'
  },
  'comma-rambler': {
    audience: 'busy moms, mostly in their 40s, who used to be active',
    audience_short: 'busy moms over 40',
    outcome: 'lose the weight, keep their energy, and not hate the process',
    core: 'consistency, not intensity, and eating enough',
    mistake1: 'they starve all day, then binge at night, and blame themselves',
    mistake2: 'they do random workouts off the internet, none of it progressive',
    mistake3: 'they compare week one to someone else’s year five, then quit',
    turning_point: 'I burned out, quit, restarted, burned out again, then built a system',
    has_proof: 'client', proofName: 'M.', proofResult: 'down 4 sizes', proofBelief: 'she had to give up bread forever',
    objection: 'they say they will start Monday, every Monday', voice: 'technical'
  }
};
const VOICES = ['blunt', 'warm', 'funny', 'technical'];

(async () => {
  const b = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
  const p = await b.newPage();
  const consoleErrs = [];
  p.on('pageerror', e => consoleErrs.push(e.message));
  await p.setRequestInterception(true);
  p.on('request', req => {
    const u = req.url();
    if (u.includes('/api/auth/me')) return req.respond({ status: 200, contentType: 'application/json', body: JSON.stringify({ user: { id: 'qa', username: 'qatrainer', displayName: 'Coach QA', isTrainer: true, trainer: { active: true } }, impersonation: null }) });
    if (u.endsWith('/api/profile')) return req.respond({ status: 200, contentType: 'application/json', body: req.method() === 'GET' ? '{"profile":null}' : '{"ok":true}' });
    req.continue();
  });
  await p.goto(URL, { waitUntil: 'networkidle2' });
  await p.evaluate(() => localStorage.clear());
  await new Promise(r => setTimeout(r, 500));

  const failures = [];
  let md = '# Content quality — sample posts\n\n_Generated by tests/content-quality.js. For each post ask: **would a trainer actually post this?**_\n\n';

  for (const [name, base] of Object.entries(PROFILES)) {
    md += `\n## Trainer: ${name}\n\n`;
    md += '```\naudience: ' + base.audience + '\noutcome:  ' + base.outcome + '\ncore:     ' + base.core + '\n```\n';

    for (const voice of VOICES) {
      const answered = Object.assign({}, base, { voice, days: { days: [1, 3, 5] }, name: 'Coach QA' });
      const profile = { answered, path: 'detailed', setupDone: true, dayZeroDone: true, appWeekday: 5 };
      const res = await p.evaluate((profile, voice) => {
        const T = window.__cpTest; T.setProfile(profile); T.setVoice(voice);
        const start = T.today(); const out = [];
        for (let i = 0; i < 28; i++) { // 4 weeks
          const d = T.addDays(start, i); const s = T.scriptFor(d); if (s.type === 'rest' || s.type === 'stories') continue;
          out.push({ type: s.type, hook: s.hook || '', cta: s.cta || '', beats: (s.beats || []).map(b => b.t + ' — ' + b.job), angleTopic: s.angle && s.angle.topic, guardHook: T.grammarGuard(s.hook || ''), guardCta: T.grammarGuard(s.cta || '') });
        }
        // also a day of stories
        const st = T.storiesFor(start).map(x => ({ slot: x.slot, line: x.line, guard: T.grammarGuard(x.line) }));
        return { posts: out, stories: st };
      }, profile, voice);

      md += `\n### Voice: ${voice}\n\n`;
      res.posts.slice(0, 6).forEach((post, i) => {
        md += `**${post.type}** — hook: “${post.hook}”\n`;
        if (post.angleTopic) md += `_angle: ${post.angleTopic}_\n`;
        post.beats.forEach(be => { md += `- ${be}\n`; });
        md += `CTA: ${post.cta.replace(/\n/g, ' / ')}\n\n`;
        // asserts
        [['hook', post.hook, post.guardHook], ['cta', post.cta, post.guardCta]].forEach(([slot, text, ok]) => {
          if (/\[object Object\]|undefined|null/.test(text)) failures.push(`${name}/${voice} ${post.type} ${slot}: bad token → ${text}`);
          if (!ok) failures.push(`${name}/${voice} ${post.type} ${slot}: grammar guard failed → ${text}`);
        });
      });
      res.stories.forEach(s => { if (!s.guard) failures.push(`${name}/${voice} story "${s.slot}": grammar guard failed → ${s.line}`); if (/\[object Object\]|undefined/.test(s.line)) failures.push(`${name}/${voice} story bad token → ${s.line}`); });

      // voice-difference check (blunt vs technical hooks) — done once per profile
      if (voice === 'technical') {
        const diff = await p.evaluate((profile) => {
          const T = window.__cpTest; const start = T.today();
          function hooks(v) { T.setProfile(profile); T.setVoice(v); const h = []; for (let i = 0; i < 6; i++) { const s = T.scriptFor(T.addDays(start, i)); if (s.hook) h.push(s.hook); } return h.join(' | '); }
          const bl = hooks('blunt'), te = hooks('technical');
          // crude overlap: shared words / total
          const setB = new Set(bl.toLowerCase().split(/\W+/)); const setT = te.toLowerCase().split(/\W+/);
          const shared = setT.filter(w => w && setB.has(w)).length; const overlap = shared / Math.max(1, setT.length);
          return { overlap: Math.round(overlap * 100) };
        }, profile);
        md += `_voice overlap blunt↔technical: ${diff.overlap}%_\n\n`;
        if (diff.overlap > 60) failures.push(`${name}: blunt/technical hooks ${diff.overlap}% identical (>60%) — voices not different enough`);
      }
    }
  }

  fs.mkdirSync(path.join(__dirname), { recursive: true });
  fs.writeFileSync(path.join(__dirname, 'sample-posts.md'), md);
  await b.close();

  console.log('=== Content QA ===');
  console.log('sample-posts.md written:', fs.statSync(path.join(__dirname, 'sample-posts.md')).size, 'bytes');
  console.log('pageerrors:', consoleErrs.length); consoleErrs.slice(0,3).forEach(e=>console.log('  pageerr:', e.slice(0,140)));
  console.log('failures:', failures.length);
  failures.slice(0, 20).forEach(f => console.log('  ✗', f));
  process.exit(failures.length ? 1 : 0);
})();
